(cl:in-package my_leapmotion-msg)
(cl:export '(CENTER-VAL
          CENTER
          DIRECTION-VAL
          DIRECTION
          DURATION-VAL
          DURATION
          HANDIDS-VAL
          HANDIDS
          ID-VAL
          ID
          NORMAL-VAL
          NORMAL
          POINTABLEIDS-VAL
          POINTABLEIDS
          POSITION-VAL
          POSITION
          PROGRESS-VAL
          PROGRESS
          RADIUS-VAL
          RADIUS
          SPEED-VAL
          SPEED
          STARTPOSITION-VAL
          STARTPOSITION
          STATE-VAL
          STATE
          GESTURETYPE-VAL
          GESTURETYPE
))