(cl:in-package my_leapmotion-msg)
(cl:export '(METACARPALBASIS-VAL
          METACARPALBASIS
          PROXIMALBASIS-VAL
          PROXIMALBASIS
          INTERMEDIATEBASIS-VAL
          INTERMEDIATEBASIS
          DISTALBASIS-VAL
          DISTALBASIS
          BTIPPOSITION-VAL
          BTIPPOSITION
          CARPPOSITION-VAL
          CARPPOSITION
          DIPPOSITION-VAL
          DIPPOSITION
          DIRECTION-VAL
          DIRECTION
          EXTENDED-VAL
          EXTENDED
          HANDID-VAL
          HANDID
          ID-VAL
          ID
          LENGTH-VAL
          LENGTH
          MCPPOSITION-VAL
          MCPPOSITION
          PIPPOSITION-VAL
          PIPPOSITION
          STABILIZEDTIPPOSITION-VAL
          STABILIZEDTIPPOSITION
          TIMEVISIBLE-VAL
          TIMEVISIBLE
          TIPPOSITION-VAL
          TIPPOSITION
          TIPVELOCITY-VAL
          TIPVELOCITY
          TOOL-VAL
          TOOL
          TOUCHDISTANCE-VAL
          TOUCHDISTANCE
          TOUCHZONE-VAL
          TOUCHZONE
          POINTABLETYPE-VAL
          POINTABLETYPE
          WIDTH-VAL
          WIDTH
))