(cl:in-package rsl-msg)
(cl:export '(ARMBASIS-VAL
          ARMBASIS
          ARMWIDTH-VAL
          ARMWIDTH
          CONFIDENCE-VAL
          CONFIDENCE
          DIRECTION-VAL
          DIRECTION
          ELBOW-VAL
          ELBOW
          GRABSTRENGTH-VAL
          GRABSTRENGTH
          ID-VAL
          ID
          PALMNORMAL-VAL
          PALMNORMAL
          PALMPOSITION-VAL
          PALMPOSITION
          PALMVELOCITY-VAL
          PALMVELOCITY
          PINCHSTRENGTH-VAL
          PINCHSTRENGTH
          R-VAL
          R
          S-VAL
          S
          SPHERECENTER-VAL
          SPHERECENTER
          SPHERERADIUS-VAL
          SPHERERADIUS
          STABILIZEDPALMPOSITION-VAL
          STABILIZEDPALMPOSITION
          T-VAL
          T
          TIMEVISIBLE-VAL
          TIMEVISIBLE
          HANDTYPE-VAL
          HANDTYPE
          WRIST-VAL
          WRIST
))