// Generated by gencpp from file rsl/ResetCalibration.msg
// DO NOT EDIT!


#ifndef RSL_MESSAGE_RESETCALIBRATION_H
#define RSL_MESSAGE_RESETCALIBRATION_H

#include <ros/service_traits.h>


#include <rsl/ResetCalibrationRequest.h>
#include <rsl/ResetCalibrationResponse.h>


namespace rsl
{

struct ResetCalibration
{

typedef ResetCalibrationRequest Request;
typedef ResetCalibrationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetCalibration
} // namespace rsl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rsl::ResetCalibration > {
  static const char* value()
  {
    return "65b5a0f951bad2a491fc17152c517af8";
  }

  static const char* value(const ::rsl::ResetCalibration&) { return value(); }
};

template<>
struct DataType< ::rsl::ResetCalibration > {
  static const char* value()
  {
    return "rsl/ResetCalibration";
  }

  static const char* value(const ::rsl::ResetCalibration&) { return value(); }
};


// service_traits::MD5Sum< ::rsl::ResetCalibrationRequest> should match 
// service_traits::MD5Sum< ::rsl::ResetCalibration > 
template<>
struct MD5Sum< ::rsl::ResetCalibrationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rsl::ResetCalibration >::value();
  }
  static const char* value(const ::rsl::ResetCalibrationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsl::ResetCalibrationRequest> should match 
// service_traits::DataType< ::rsl::ResetCalibration > 
template<>
struct DataType< ::rsl::ResetCalibrationRequest>
{
  static const char* value()
  {
    return DataType< ::rsl::ResetCalibration >::value();
  }
  static const char* value(const ::rsl::ResetCalibrationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rsl::ResetCalibrationResponse> should match 
// service_traits::MD5Sum< ::rsl::ResetCalibration > 
template<>
struct MD5Sum< ::rsl::ResetCalibrationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rsl::ResetCalibration >::value();
  }
  static const char* value(const ::rsl::ResetCalibrationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsl::ResetCalibrationResponse> should match 
// service_traits::DataType< ::rsl::ResetCalibration > 
template<>
struct DataType< ::rsl::ResetCalibrationResponse>
{
  static const char* value()
  {
    return DataType< ::rsl::ResetCalibration >::value();
  }
  static const char* value(const ::rsl::ResetCalibrationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RSL_MESSAGE_RESETCALIBRATION_H
