// Generated by gencpp from file rsl/ResetCalibrationResponse.msg
// DO NOT EDIT!


#ifndef RSL_MESSAGE_RESETCALIBRATIONRESPONSE_H
#define RSL_MESSAGE_RESETCALIBRATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rsl
{
template <class ContainerAllocator>
struct ResetCalibrationResponse_
{
  typedef ResetCalibrationResponse_<ContainerAllocator> Type;

  ResetCalibrationResponse_()
    {
    }
  ResetCalibrationResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::rsl::ResetCalibrationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rsl::ResetCalibrationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ResetCalibrationResponse_

typedef ::rsl::ResetCalibrationResponse_<std::allocator<void> > ResetCalibrationResponse;

typedef boost::shared_ptr< ::rsl::ResetCalibrationResponse > ResetCalibrationResponsePtr;
typedef boost::shared_ptr< ::rsl::ResetCalibrationResponse const> ResetCalibrationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rsl::ResetCalibrationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rsl::ResetCalibrationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rsl

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rsl': ['/home/dzhi/catkin_ws/src/rsl/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rsl::ResetCalibrationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rsl::ResetCalibrationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsl::ResetCalibrationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsl::ResetCalibrationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsl::ResetCalibrationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsl::ResetCalibrationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rsl::ResetCalibrationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::rsl::ResetCalibrationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rsl::ResetCalibrationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rsl/ResetCalibrationResponse";
  }

  static const char* value(const ::rsl::ResetCalibrationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rsl::ResetCalibrationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
";
  }

  static const char* value(const ::rsl::ResetCalibrationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rsl::ResetCalibrationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetCalibrationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rsl::ResetCalibrationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::rsl::ResetCalibrationResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // RSL_MESSAGE_RESETCALIBRATIONRESPONSE_H
