// Generated by gencpp from file my_leapmotion/ResetCalibration.msg
// DO NOT EDIT!


#ifndef MY_LEAPMOTION_MESSAGE_RESETCALIBRATION_H
#define MY_LEAPMOTION_MESSAGE_RESETCALIBRATION_H

#include <ros/service_traits.h>


#include <my_leapmotion/ResetCalibrationRequest.h>
#include <my_leapmotion/ResetCalibrationResponse.h>


namespace my_leapmotion
{

struct ResetCalibration
{

typedef ResetCalibrationRequest Request;
typedef ResetCalibrationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetCalibration
} // namespace my_leapmotion


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_leapmotion::ResetCalibration > {
  static const char* value()
  {
    return "65b5a0f951bad2a491fc17152c517af8";
  }

  static const char* value(const ::my_leapmotion::ResetCalibration&) { return value(); }
};

template<>
struct DataType< ::my_leapmotion::ResetCalibration > {
  static const char* value()
  {
    return "my_leapmotion/ResetCalibration";
  }

  static const char* value(const ::my_leapmotion::ResetCalibration&) { return value(); }
};


// service_traits::MD5Sum< ::my_leapmotion::ResetCalibrationRequest> should match 
// service_traits::MD5Sum< ::my_leapmotion::ResetCalibration > 
template<>
struct MD5Sum< ::my_leapmotion::ResetCalibrationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_leapmotion::ResetCalibration >::value();
  }
  static const char* value(const ::my_leapmotion::ResetCalibrationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_leapmotion::ResetCalibrationRequest> should match 
// service_traits::DataType< ::my_leapmotion::ResetCalibration > 
template<>
struct DataType< ::my_leapmotion::ResetCalibrationRequest>
{
  static const char* value()
  {
    return DataType< ::my_leapmotion::ResetCalibration >::value();
  }
  static const char* value(const ::my_leapmotion::ResetCalibrationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_leapmotion::ResetCalibrationResponse> should match 
// service_traits::MD5Sum< ::my_leapmotion::ResetCalibration > 
template<>
struct MD5Sum< ::my_leapmotion::ResetCalibrationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_leapmotion::ResetCalibration >::value();
  }
  static const char* value(const ::my_leapmotion::ResetCalibrationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_leapmotion::ResetCalibrationResponse> should match 
// service_traits::DataType< ::my_leapmotion::ResetCalibration > 
template<>
struct DataType< ::my_leapmotion::ResetCalibrationResponse>
{
  static const char* value()
  {
    return DataType< ::my_leapmotion::ResetCalibration >::value();
  }
  static const char* value(const ::my_leapmotion::ResetCalibrationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_LEAPMOTION_MESSAGE_RESETCALIBRATION_H
